- hosts: localhost
  vars_prompt:
    - name: container_name
      prompt: "Enter the Container Name"
      private: no

  tasks:
  - yum_repository: 
                description: Docker yum 
                name: docker2
                baseurl: https://download.docker.com/linux/centos/7/x86_64/stable/
                gpgcheck: no
                state: present
            
  - package:
                name: "docker-ce-18.09.1-3.el7.x86_64"
                state: present
                skip_broken: yes
  - name: Docker service start
          service:
                name: docker
                state: started
                enabled: yes

  - name: Sdk install
          command: "pip3 install docker"

  - name: Launch docker container with ssh enabled image
    docker_container:
      name: "{{ container_name }}"
      image: piyush1515/dockerize-ssh:latest
      interactive: yes
      tty: yes
      detach: yes
      state: started
  
  - name: Get info of the container
    docker_container_info:
      name: "{{ container_name }}" 
    register: result

  - name: Printing IP Address
    debug:
            msg: "{{ result.container.NetworkSettings.IPAddress }}"

  - name: Update Container IP in inventory
    blockinfile:
      path: ip.txt
      block: |
              [docker]
              {{ result.container.NetworkSettings.IPAddress }} ansible_user=root ansible_password=piyushansible15 ansible_connection=ssh
